modify scripts

diff --git a/.github/workflows/block-merge.yml b/.github/workflows/block-merge.yml
--- a/.github/workflows/block-merge.yml
+++ b/.github/workflows/block-merge.yml
@@ -13,8 +13,9 @@ jobs:
   block-merge:
     runs-on: ubuntu-latest
     steps:
-      - name: Toggle merge status
+      - name: Toggle merge status (PR)
         id: toggle-merge-status
+        if: ${{ github.event_name == 'pull_request' }}
         run: |
           ENDPOINT_URL="${{ github.api_url }}/repos/${{ github.repository }}/deployments"
           curl -s -X GET \
@@ -38,10 +39,23 @@ jobs:
                         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"      \
                         -H "X-GitHub-Api-Version: 2022-11-28"    \
                         "$statuses_url?per_page=1" | jq -r '.[0].state')
-          if [ "$status" == 'active' ] || [ "$status" == 'inactive' ]; then
+          if [ "$status" == 'success' ] || [ "$status" == 'inactive' ]; then
             echo '[INFO] related deployment status is ${status}.'
             exit 0
           else
             echo '[ERROR] related deployment status is not in [active, inactive].'
+            exit 1
+          fi
+
+      - name: Toggle merge status (Deployment status)
+        id: toggle-merge-status
+        if: ${{ github.event_name == 'deployment_status' }}
+        run: |
+          status=${{ github.event.deployment_status }}
+          if [ "$status" == 'success' ]; then
+            echo '[INFO] related deployment status is ${status}.'
+            exit 0
+          else
+            echo '[ERROR] related deployment status is not success.'
             exit 1
           fi
