modify

diff --git a/.github/workflows/block-merge.yml b/.github/workflows/block-merge.yml
--- a/.github/workflows/block-merge.yml
+++ b/.github/workflows/block-merge.yml
@@ -17,20 +17,26 @@ jobs:
         id: toggle-merge-status
         run: |
           ENDPOINT_URL="${{ github.api_url }}/repos/${{ github.repository }}/deployments"
-          STATUSES_URL=$(curl -s -X GET \
+          statuses_url=$(curl -s -X GET \
                               -H "Accept: application/vnd.github+json" \
-                              -H "Authorization: Bearer ${TOKEN}"      \
+                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"      \
                               -H "X-GitHub-Api-Version: 2022-11-28"    \
                               "$ENDPOINT_URL?sha=${{ github.sha }}" | jq -r '.[0].statuses_url')
-          status=$(curl -s -X GET \
-                        -H "Accept: application/vnd.github+json" \
-                        -H "Authorization: Bearer ${TOKEN}"      \
-                        -H "X-GitHub-Api-Version: 2022-11-28"    \
-                        "$STATUSES_URL?per_page=1" | jq -r '.[0].state')
-          if [ "$status" == 'active' ] || [ "$status" == 'inactive' ]; then
+          if echo "$statuses_url" | grep -q $ENDPOINT_URL; then
             echo '[INFO] related deployment is found.'
-            exit 0
           else
             echo '[ERROR] related deployment is not found.'
+            exit 1
+          fi
+          status=$(curl -s -X GET \
+                        -H "Accept: application/vnd.github+json" \
+                        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"      \
+                        -H "X-GitHub-Api-Version: 2022-11-28"    \
+                        "$statuses_url?per_page=1" | jq -r '.[0].state')
+          if [ "$status" == 'active' ] || [ "$status" == 'inactive' ]; then
+            echo '[INFO] related deployment status is ${status}.'
+            exit 0
+          else
+            echo '[ERROR] related deployment status is not in [active, inactive].'
             exit 1
           fi
